source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'IronSourceSwiftDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

    pod 'IronSourceSDK' 
  # Pods for IronSourceSwiftDemoApp
    pod 'IronSourceHyprMXAdapter','4.3.10.0'
end
